 export default { 
     CHANGE_TRACK: 'CHANGE_TRACK',
     PLAY: 'PLAY',
     PAUSE:'PAUSE',
     STOP: 'STOP',
     SHUFFLE: 'SHUFFLE',
     REORDER:'REORDER',
     CHANGE_VOLUME:'CHANGE_VOLUME',
     SET_START_TIME: 'SET_START_TIME',
     SET_STOP_TIME: 'SET_STOP_TIME',
     SET_CURRENT_TIME: 'SET_CURRENT_TIME',
     MAXIMISE: 'MAXIMISE',
     MINIMISE: 'MINIMISE'
}
