/**
 * Store action types
 * @enum {string}
 */
const actionTypes = {
  CHANGE_TRACK: "CHANGE_TRACK",
  PLAY: "PLAY",
  PAUSE: "PAUSE",
  STOP: "STOP",
  SHUFFLE: "SHUFFLE",
  UPDATE_PLAYLIST: "UPDATE_PLAYLIST",
  CHANGE_VOLUME: "CHANGE_VOLUME",
  SET_START_TIME: "SET_START_TIME",
  SET_STOP_TIME: "SET_STOP_TIME",
  SET_CURRENT_TIME: "SET_CURRENT_TIME",
  SET_TIME_LEFT: "SET_TIME_LEFT",
  SEEK: "SEEK",
  SET_REPEAT_MODE: "SET_REPEAT_MODE",
};

export default actionTypes;
